name: CI

on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: self-hosted
    steps:
    - name: 'Get Config'
      working-directory: /root/ci
      shell: bash
      run: 'touch bajskorv'
