name: CI

on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: self-hosted
    steps:
    - name: 'Get Config'
#      working-directory: /home/kieeps/ci
      shell: bash
      run: 'pwd'
