name: CI

on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: self-hosted
    steps:
    - name: 'Get PWD'
#      working-directory: /home/kieeps/ci
      shell: bash
      run: 'pwd'
    - name: 'Get user'
      shell: bash
      run: 'echo $USER'
    - name: 'create file'
      shell: bash
      run: 'touch /root/ci/bajskorv123'
